### ISSUE TITLE
ERROR in Cannot read property 'loadChildren' of undefined

### ISSUE THREAD

**Issue by s4lvo** [gquinteros93/same-path-for-different-modules#1]
If you run ng build --prod you have the following error:

ERROR in Cannot read property 'loadChildren' of undefined

**Comment by gquinteros93** [comment]
Hi @s4lvo , thanks for reporting the issue. 

I was able to run the build using: ```npm run build``` and ```npm run build --prod```.
Can you trying using those commands?

Here is a screenshot of my terminal after ```npm run build```

![image](https://user-images.githubusercontent.com/53574912/76817302-34d68d00-67e1-11ea-9c1f-ab5210898012.png)

**Comment by shripatki** [comment]
hey hi German Quinteros actually when we run the prod build or aot in dev environment then we will get the error as cannot read property load children of undefined.

**Comment by shripatki** [comment]
@mgechev can you please look into this issue

**Comment by gquinteros93** [comment]
Hi @shripatki . Did you get that error cloning/downloading this repo and running it in your local environment? Or, Is that error happening in your own project? If that is the case, Can you give me more information about your Project (Angular Version, Nod, and npm version)? 

Thanks.

**Comment by shripatki** [comment]
@gquinteros93 yes i have cloned this repo. still was getting same error then i upgraded the angular version to angular 9 my issue gets resolved thanks

**Comment by gquinteros93** [comment]
Hi @shripatki , thanks for the update. I tested in my local environment with aot and I had the same issue. I have tried to resolve it but I didn't have success. I will update the project to Angular 9 to solve it. Then I will see if there is anything I can do for Angular 8.
Also, I have a project working with Angular 7 that uses this approach with AOT and works good. 
It seems to be an error in Angular 8.

**Comment by gquinteros93** [comment]
@shripatki , you were right, updating the Angular version from 8 to 9 fixed the AOT bug and now the project works as expected. 
Thanks for your help.
The solution to this bug was merged in this [commit](https://github.com/gquinteros93/same-path-for-different-modules/commit/09e27d094c72f30cc3fa13e186962043c8b0e4d8)
Because of that, I close the issue.
